### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by unixorn** [sirshikher/zsh-om#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license.

Please add a license - if you don't have one in mind,  I recommend [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

**Comment by sirshikher** [comment]
> I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license.
> 
> Please add a license - if you don't have one in mind, I recommend [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Hi @unixorn, sorry for the late reply. I have added a license.
